if: (type = push AND branch IN (master, module_7)) OR (type = pull_request)
sudo: required
services:
  - docker

env:
  global:
    - FLASK_APP=todo_app.app
    - FLASK_ENV=production
    - COL_1="Not Started"
    - COL_2="In Progress"
    - COL_3="Completed"
  jobs:
    - COMPOSE_VERSION: 1.27.4

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - echo "running tests for JB ToDo app"
  - docker-compose --file docker-compose-travis.yml up --build
