if: "(type = push AND branch IN (main, module_11)) OR (type = pull_request)"
os: linux
dist: bionic
sudo: required

services:
  - docker

env:
  global:
    - FLASK_APP=todo_app.app
    - FLASK_ENV=production
    - secure: "mqKPFa6IPwR2Y9GtZOTG5FpIsY/bpXsdB1BMsj3pR0g+98JMZb6Z9lNNmpDC07PQjKa8vG7gmUW+w5wP5+0u2Nv5MA43FrTWqwNgCG865ddqB9IbefSMNWhgQ5eMC75FeplkyChNy6hn8VH/Vz/oPBBxryqU3E6dAVrqH4QOWCjz1pnPTM87GvO2O8yECV7N5OrL3/8ZD4fgYfwOpPBr8NPzCls2zJEekPPb9wou/sa9e3uw3AaY3jn8e16j8pZnDxfnboEpgG8Vw28KVEdsf7PYxcz+u7gF198xGoq6CKmhJBN/vd9eW5IHpxUj/Qicp/gfbRWRDsCKJ06ANdhjFZ+9Z/7cagbbSztJSLU6vHdxEkYkMLVsNPcuM6GqjHfLPGKYCCImRduvhhfAfnjINkPgEkpUciVw88jhTL6eKRtKuq0qMJJJJT7E2moO+1Bt4n7tLjBRHoU4K0rXPjX3X2Yeh7jxdPcpAr0nWwy/liRKd7r0eklXYjSTks3eNnTGTJs7lwXbWuMQZauW3LNiI4WbwvO+b2pbEfDRBBw5c5PHxQbJp1Mdm5mtxliYYHYHEIjLvtoVeemUIKKccJvkf7gbNa1CoVT/4bfqNeCL4K4GZ31WaDc7uW8Ak11bxpBqSlQsUDjvx3LPiKaalgDZE3lc9B3PkJxEUWykiDhvk2I="
    - MONGO_DB="todo_app_db"
    - COL_1="Not Started"
    - COL_2="In Progress"
    - COL_3="Completed"
    - DOCKER_USERNAME="jaybee1971"
    - secure: M8fRVi+KFg+KJoVhrdYJwrQWwSuiL8EI0H78FUeVHF8HwnZL70j6rf/cb+xZi0lN2NFQtDlMxoSR4W3kQh2EO6VBsuJJ0QT5Ngv6zUh9F+Bk89BVqC1Qg9cutQCiKjL2Yk78lqR0q+/PdxV7VjPRXa9MT42ViYlBcXLFpKn3i+y9Z4soWJ0qrtcqMJmz8E9Xq5crG5ndGOWTTJa6yeEw1XLcMJ5m1UPRajor0Mxvy8M+S725QLYHBj3fQp5eId25UTcWt4A4uQf+xPkMg/1dEdtGG5P5mLaaOhMRpIvWeh27IFjTyPH5XIO444o+zKtjI3X5qF8Ypt7v+lRuLYusWwqaXH2pPo3hUFq9E0uuZkIEI1vJKSvGijT1/kAx0F710U9yb4vnxNgzO0hDtn/4lmbytcuSa06rL8yQI1eKM4EfKqpQTgcR8BD2Kuh08HYf+v79bMk2m9+uNduRkJDPd6Nu82OEWyYB+IyYbyt2KwqboHWteetrmhD7FjRkl1Jms3nX8eQ8FGir+ZHoc4uy8gqt3OGxxcHIM7dzcBkdBykBjVgmpw8lnp1KleIaqleB1G3v+Mg7SHHSDssss5ict5s/RIMllPhnqGUMHarwymx2KGyutmGsaDuWcMmKYJXUQYLANmvor019ozE+Rb+fEqW8jcpJd1TfdGkZytYfXxs=
    - secure: "EC7EViOfY8tVGfNAqQhd0jLj8ECQypb3gGVyMHa9/QzSo8+Hbm491Z/ttyDK0vn1+Ju9kZm3s/MMTCiZV6vtiy4LrBwfb5BXo02N4khPrV73huY/GIWCrOD+41ALAgoqQA9ZUMr9l1exj4PakLmxROs2Quv+40kY0A3spHCapbgxbERUoe+7IS5PkGjjAZ3aOYxvO4S4ZXjmCqd4sttZhdci43BYoH2XCm3ijuf1n3rozQCVtkfXDLLIQqezKHPl7lZ1ISEbRiRqf+fLGYPHVIg0FKbuPntY/WYoefmEmEs3nfFzzZ0C0JUFnWEgVE7W8agobNOOVlSrF01ymHZVgixPyqU32rbHTAfqoFNnuVsQod2bE0FQ2S4D75yFKFsj65O3pJ2TOGh2jnSZ00QAcFqQ1eyoZuiYr0eQlNBzcDtINCgUQ9TvdiCSolwDKFOuEjHgv3RpUnxRYaJYamCFChCSD7Wxpnl7nIa1jv2wSQAFK+6wSKojmP2P10+aUbL4Mzq+6j2Vb6xqi8xfclRBWpfmtL/rseEIkwT+Mx1eXD3w3Tk/Kfd+RPAzIGcV7WAG4+tN45G7hTlDUGLkp6PE6560jt/8R9PXMnSZ97W58qmrovtJIuAs6lI5cJwm6W2ZF8DkKRqFmdOBTOvmOJKOyI1Hz2RCzbRTGt/DkEgO6Qc="
    - DOCKER_COMPOSE_VERSION=1.27.4
    - IMAGE_NAME=jaybee1971/todo_app
    - DOCKER_BUILDKIT=1
    - COMPOSE_DOCKER_CLI_BUILD=1
    - secure: "cQVzPbj30nkfcBijBr7AoHYmVh3lbgSSUuBsoWTtkhirXnhR91uRgzn6IarmuAUb8Lo2rKjfV4oL+/4QaO7bRB5EaroFoRWp5Np7Q4z72HGOWgcfKIKmvZAAuyPNJYxP7vqR3SEcLtbeO+8UWWn/M5eiFBp2lPBwfTYTYp52K6V3EU36PECigWgTURcnGqooqZ8eN21brGC1pQ37NUI6wl0dih/sFRoL5Z+hWWsjB+6Mj0nJJOYQdvHMiBLSeXHUc4sYhYM5cEe1EXhQ8pKJBCABhHQyaCgjICYbzAM6kSn1ObjKit02HHkbcz34d4/JXmdS+0ya98z0HyeU7MnJkrzf5W5QHAaLakeZNxhrGO1S0pS+vWRa6OgPXeqoxL4OXcdMIDjNQK6N0QPOp5XA3rUrpZdB/MkrA7T8EEeX/84Qb0WP5JFHVSfBoL/p/sPg548jAWPdmf2XNpwa3lDozPkJyoEh+yybZ94OvgWTwyauvvuOXK0nTlVy78VwJQz7AUdOOlJresG/35nFGGxDhgqhi6bOoZzjm9czdIlb9Ed6+zD4XsKTs6l9gME984XpMM2rRT6x5z8XNxWjzE6uleFQ27cb6kpUKz/DQYmBba2mYA+W56yWuyQ905cGKofh7Q6bWobdw5paFa1/7DZQajo4DrUxhzM8Znh2wenfQ+0="

before_install:
  - set -e
  # install docker
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=5:19.03.8~3-0~ubuntu-bionic
  - docker info
  # install docker compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin

script:
  - docker-compose --file docker-compose-travis.yml build --build-arg BUILDKIT_INLINE_CACHE=1 
  - docker-compose --file docker-compose-travis.yml up --exit-code-from todoapp

deploy:
  - provider: script
    script: bash docker_push
    on:
      branch: module_11

notifications:
  email:
    recipients:
      - jay.bee71@outlook.com
    on_success: never
    on_failure: always
