version: "3"

services:
  todoapp:
    build:
      context: ./
      dockerfile: Dockerfile
      target: todo-dev
    image: todo-app:dev
    ports: 
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./:/code/:cached
