version: "3"

services:
  todoapp:
    image: todo-app:todo-test
    build:
      context: ./
      dockerfile: Dockerfile
      target: todo-test
      cache_from: 
        - todo-app:latest
    ports: 
      - "5000:5000"
    environment:
      FLASK_APP : "${FLASK_APP}"
      FLASK_ENV : "${FLASK_ENV}"
      MONGO_URL : "${MONGO_URL}"
      MONGO_DB : "${MONGO_DB}"
      COL_1 : "${COL_1}"
      COL_2 : "${COL_2}"
      COL_3 : "${COL_3}"
