#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build --cache-from $CACHE_IMAGE:latest --target todo-heroku --tag $CACHE_IMAGE:${TRAVIS_COMMIT} .
docker push $CACHE_IMAGE:${TRAVIS_COMMIT}
echo docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
docker tag $CACHE_IMAGE:${TRAVIS_COMMIT} registry.heroku.com/jaybee1971-todoapp/web
docker push registry.heroku.com/jaybee1971-todoapp/web
heroku container:release web -a jaybee1971-todoapp
